# Generated by Django 5.1.5 on 2025-04-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
